### PR TITLE
WIP: Replace Utf8Json with System.Text.Json

### PR DESCRIPTION
**Pull request by Dolfik1**

### CODE REVIEW

**Comment by Dolfik1** [comment]
I just uploaded a preview version of Funogram with System.Text.Json to nuget:
Funogram.2.1.0-preview1
Funogram.Telegram.7.0.0.3-preview1

@ForNeVeR

**Comment by ForNeVeR** [comment]
Ok I'll check this tonight.

**Comment by ForNeVeR** [comment]
@Dolfik1 ok I did some manual testing, and the packages seem to work well!

**Comment by Dolfik1** [comment]
> @Dolfik1 ok I did some manual testing, and the packages seem to work well!

I've encountered an issue with the deserialization of the FSharpOption type and replaced the default STJ deserializer with a custom one. Now, STJ appears to be stable. I will release a new version of Funogram (3.0.0 and *.Telegram 7.0.0.3).

**Pull request merged**
